#!/usr/bin/env python3
"""Generate the public CLI reference from the live Typer command tree."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

from typer.main import get_command

from forge import __version__
from forge.cli_v2 import app

OUTPUT = Path("docs/CLI_REFERENCE.md")
HELP_WIDTH = 80


def command_paths() -> list[tuple[str, ...]]:
    root = get_command(app)
    paths: list[tuple[str, ...]] = []

    def walk(command: Any, prefix: tuple[str, ...]) -> None:
        if not callable(getattr(command, "list_commands", None)) or not callable(getattr(command, "get_command", None)):
            return
        context = command.context_class(command, info_name=prefix[-1] if prefix else "forge")
        for name in command.list_commands(context):
            child = command.get_command(context, name)
            if child is None:
                continue
            path = (*prefix, name)
            paths.append(path)
            walk(child, path)

    walk(root, ())
    return paths


def _plain_help_command() -> Any:
    """Build a transient command tree whose help is independent of Rich/TTY state."""
    root = get_command(app)

    def disable_rich(command: Any) -> None:
        if hasattr(command, "rich_markup_mode"):
            command.rich_markup_mode = None
        children = getattr(command, "commands", None)
        if isinstance(children, dict):
            for child in children.values():
                disable_rich(child)

    disable_rich(root)
    return root


def _help(path: tuple[str, ...]) -> str:
    # Generated documentation uses Click's plain formatter because Rich also
    # derives rendering details from TTY state, locale, and CI environment.
    # The live CLI remains Rich-enabled; only this transient tree is changed.
    command = _plain_help_command()
    context = command.context_class(
        command,
        info_name="forge",
        terminal_width=HELP_WIDTH,
        max_content_width=HELP_WIDTH,
    )
    for name in path:
        child = command.get_command(context, name)
        if child is None:
            full_name = " ".join(("forge", *path))
            raise RuntimeError(f"help command disappeared from the runtime tree: {full_name}")
        command = child
        context = command.context_class(
            command,
            info_name=name,
            parent=context,
            terminal_width=HELP_WIDTH,
            max_content_width=HELP_WIDTH,
        )
    return command.get_help(context).strip()


def render() -> str:
    paths = command_paths()
    lines = [
        "# FORGE CLI reference",
        "",
        f"Generated from the FORGE {__version__} runtime command tree. Do not edit this file by hand; run",
        "`uv run python scripts/generate_cli_reference.py` after changing CLI registration or options.",
        "",
        "Commands that expose `--json` emit one JSON document on stdout on success. Domain errors emit",
        "one JSON document on stderr and exit nonzero. Progress output is suppressed in JSON mode.",
        "",
        "## Command index",
        "",
    ]
    lines.extend(f"- `forge {' '.join(path)}`" for path in paths)
    lines.extend(["", "## `forge --help`", "", "```text", _help(()), "```", ""])
    for path in paths:
        command = " ".join(("forge", *path))
        lines.extend([f"## `{command}`", "", "```text", _help(path), "```", ""])
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail when the checked-in reference is stale")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"{OUTPUT} is stale; regenerate it", file=sys.stderr)
            return 1
        print(f"{OUTPUT} matches the live CLI")
        return 0
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT} ({len(command_paths())} command paths)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
